### PR TITLE
Enable minify

### PR DESCRIPTION
**Pull request by mdrlzy**
## :rocket: Summary
Reduce apk size
`ark-navigator-arm64-v8a-apk` 34.2 MB -> 28.9 MB

### CODE REVIEW

**Review by hieuwu — COMMENTED** [review]
Looks good. It would be more descriptive if we keep minifyEnable property and set to true explicitly

**Review by hieuwu — APPROVED** [review]
Interesting number. 🚀

**Comment by mdrlzy** [comment]
> Looks good. It would be more descriptive if we keep minifyEnable property and set to true explicitly

`minifyEnable` does not allow you to turn off obfuscation. I want to leave obfuscation disabled to avoid problems with json fields, reading crash logs and so on, and this is useless since the project is open source

**Comment by hieuwu** [comment]
> > Looks good. It would be more descriptive if we keep minifyEnable property and set to true explicitly
> 
> `minifyEnable` does not allow you to turn off obfuscation. I want to leave obfuscation disabled to avoid problems with json fields, reading crash logs and so on, and this is useless since the project is open source

That makes sense

**Pull request merged**
