### PR TITLE
Restructure project

### PR DESCRIPTION
**Pull request by hieuwu**
### ⭐️ Summary
Restructure project from `space.taran` to `dev.arkbuilders`

### 🖼 Screenshot
Screenshot 2023-10-14 at 22 05 32

Screenshot 2023-10-14 at 20 59 42

### CODE REVIEW

**Comment by tuancoltech** [comment]
@hieuwu @kirillt : This might be conflicting with what we've been doing in this branch: `rename-package`?
We are doing the same work !

**Comment by hieuwu** [comment]
> @hieuwu @kirillt : This might be conflicting with what we've been doing in this branch: `rename-package`? We are doing the same work !

No worries, there might be miscommunication here . As @kirillt  told me to work on this. Although this conflicts with `rename-package`, let's use this as a reference because `rename-package` does not work. Feel free to close this PR when the job is done

**Comment by kirillt** [comment]
@tuancoltech sorry, I indeed asked @hieuwu to help with this.. But we can compare the changes in both PRs since it's error-prone kind of work, so both PRs are useful.

**Comment by tuancoltech** [comment]
@hieuwu We've finalized the changes in `rename-package` which serves the same purpose as of this PR.
Could you take a look and see if there's any differences between the two?

https://github.com/ARK-Builders/ARK-Navigator/pull/387

**Comment by kirillt** [comment]
Good PR, we've merged the similar PR, seems to be almost same.

**Pull request closed without merging**
