### PR TITLE
#153: Faster PDF preview generation

### PR DESCRIPTION
**Pull request by kirillt**
#153 
Adopting new PDF functionality from [arklib](https://github.com/ARK-Builders/arklib/)
See https://github.com/ARK-Builders/arklib/issues/11 and https://github.com/ARK-Builders/arklib-android/issues/7 for details

### CODE REVIEW

**Comment by kirillt** [comment]
Awesome that we touched base with and wired some advanced stuff from Rust side to Kotlin.
But here is performance degradation, at the moment.

Manual testing on a folder with many big PDF files produced the following results:
* this branch: 115 seconds
* `main` branch: 40 seconds

The folder contains 469 documents, size of each is from 41KB to 21MB.

Detailed rendering logs:
[pdf-previews_this.txt](https://github.com/ARK-Builders/ARK-Navigator/files/9079840/pdf-previews_this.txt)
[pdf-previews_main.txt](https://github.com/ARK-Builders/ARK-Navigator/files/9079841/pdf-previews_main.txt)

**Comment by kirillt** [comment]
Some of documents are rendered faster with this version, and some are faster with `main` version.
Yes, it also depends on configurable quality, but here are refined logs for side-by-side comparison:
[this.log](https://github.com/ARK-Builders/ARK-Navigator/files/9079901/this.log)
[main.log](https://github.com/ARK-Builders/ARK-Navigator/files/9079902/main.log)

**Comment by kirillt** [comment]
Here is extensive, readable report of 383 files:
[pdf-performance.txt](https://github.com/ARK-Builders/ARK-Navigator/files/9079952/pdf-performance.txt)

Previews for these 7 files are rendered faster by new version:
```
/storage/emulated/0/Papers/biomath/05-14_mem_module.PDF
`this`: 1287 ms
`main`: 1535 ms
    Nice! `this` is 19.26% faster than `main`
--
/storage/emulated/0/Papers/cognitive/s41235-021-00334-w.pdf
`this`: 13932 ms
`main`: 15856 ms
    Nice! `this` is 13.80% faster than `main`
--
/storage/emulated/0/Papers/Flash Boys 2.0 - Frontrunning, Transaction Reordering, and Consensus Instability
`this`: 14413 ms
`main`: 15056 ms
    Nice! `this` is 4.46% faster than `main`
--
/storage/emulated/0/Papers/Per Mertin Lof - The Definition of Random Sequences.pdf
`this`: 2794 ms
`main`: 6616 ms
    Nice! `this` is 136.79% faster than `main`
--
/storage/emulated/0/Papers/Scalable, transparent, and post-quantum secure computational
`this`: 2668 ms
`main`: 4579 ms
    Nice! `this` is 71.62% faster than `main`
--
/storage/emulated/0/Papers/The Knowledge Complexity of Interactive Proof-System.pdf
`this`: 4342 ms
`main`: 5655 ms
    Nice! `this` is 30.23% faster than `main`
--
/storage/emulated/0/Papers/TrueBit.pdf
`this`: 3237 ms
`main`: 12890 ms
    Nice! `this` is 298.20% faster than `main`
```

Attaching those 7 files here:
[nice.zip](https://github.com/ARK-Builders/ARK-Navigator/files/9079959/nice.zip)

Full archive (487MB):
https://www.taran.space/dev/pdf-test.zip

**Comment by nagato-chan** [comment]
> Awesome that we touched base with and wired some advanced stuff from Rust side to Kotlin. But here is performance degradation, at the moment.
> 
> Manual testing on a folder with many big PDF files produced the following results:
> 
>     * **this branch: 115 seconds**
> 
>     * **`main` branch: 40 seconds**
> 
> 
> The folder contains 469 documents, size of each is from 41KB to 21MB.

We could switch to Medium Quality for rendering preview. I have tested it and it indicated that it will significantly cut down the time cost while providing previews with similar quality.

**Comment by kirillt** [comment]
```
java.lang.UnsatisfiedLinkError: No implementation found for long space.taran.arknavigator.mvp.model.repo.index.ResourceIdKt.computeIdNative(long, java.lang.String) (tried Java_space_taran_arknavigator_mvp_model_repo_index_ResourceIdKt_computeIdNative and Java_space_taran_arknavigator_mvp_model_repo_index_ResourceIdKt_computeIdNative__JLjava_lang_String_2)
	at space.taran.arknavigator.mvp.model.repo.index.ResourceIdKt.computeIdNative(Native Method)
	at space.taran.arknavigator.mvp.model.repo.index.ResourceIdKt.computeId(ResourceId.kt:14)
	at space.taran.arknavigator.mvp.model.repo.index.ResourceMeta$Companion.fromPath(ResourceMeta.kt:30)
	at space.taran.arknavigator.mvp.model.repo.index.PlainResourcesIndex$reindexRoot$2.invokeSuspend(PlainResourcesIndex.kt:167)
	at space.taran.arknavigator.mvp.model.repo.index.PlainResourcesIndex$reindexRoot$2.invoke(Unknown Source:8)
	at space.taran.arknavigator.mvp.model.repo.index.PlainResourcesIndex$reindexRoot$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at space.taran.arknavigator.mvp.model.repo.index.PlainResourcesIndex.reindexRoot$app_release(PlainResourcesIndex.kt:133)
	at space.taran.arknavigator.mvp.model.repo.index.PlainResourcesIndex$reindex$2.invokeSuspend(PlainResourcesIndex.kt:94)
	at space.taran.arknavigator.mvp.model.repo.index.PlainResourcesIndex$reindex$2.invoke(Unknown Source:8)
	at space.taran.arknavigator.mvp.model.repo.index.PlainResourcesIndex$reindex$2.invoke(Unknown Source:4)
	at space.taran.arknavigator.utils.CoroutineUtilsKt$withContextAndLock$2.invokeSuspend(CoroutineUtils.kt:20)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by kirillt** [comment]
State of the things: after recent changes in `arklib` Navigator from this PR hangs up during rendering previews for PDFs. Sometimes, after 1 document, sometimes after 10.

If we look closer at this thread: https://github.com/ajrcarey/pdfium-render/issues/59, we'll notice that changes in `arklib` are almost identical to the code sample kindly provided by @ajrcarey :) And he put it clearly that this snippet isn't tested and that Pdfium itself is not thread-safe :) Although it could work.

I suggest to do the simplest thing for this moment and ensure that all PDF previews are generated sequentially. We could batch PDF resources into separate set and process it from a dedicated thread/coroutine. @mdrlzy probably you could implement it?

**Comment by kirillt** [comment]
Also this feature could help us to debug this https://github.com/ARK-Builders/arklib/issues/33

**Comment by kirillt** [comment]
Sequential previews generation benchmark:
* `main` branch with parallel generation disabled
    build: https://github.com/ARK-Builders/ARK-Navigator/actions/runs/3931502951
* this PR version
    build: https://github.com/ARK-Builders/ARK-Navigator/actions/runs/3925701199

OS: Android 11
Device: Samsung Galaxy Note 10+
Benchmark data: 477 PDF files, 857 MB total

Results (total indexing time, previews/thumbnails generation is the bottleneck):
**main: 1 min 5 sec**
**this PR: 9 min 43 sec**

**Comment by kirillt** [comment]
Data size of outputs in sequential tests:
**main: 84.7 MB**
**this PR (medium): 87.4 MB**

Data sizes of individual previews slightly differ, some are heavier in this PR and some are lighter comparing to `main`.

Dimensions of the previews are the same in both versions.
I don't see significant difference in quality of previews.

Samples of the previews (click to see in the original size):

_(main)_

_(this PR)_

Previews of landscape-oriented documents are generated by this PR version in portrait layout, they are just turned clockwise. Not sure if it is a problem, anyway should be possible to fix easily:

_(main)_

_(this PR)_

**Comment by kirillt** [comment]
I think we should merge this PR, but also implement:
- [ ] Sequential rendering of previews for PDF resources
- [ ] Thumbnails generation should be separated from previews, so it could remain parallel for all kinds of resources

We need to take this task in-scope:
- [ ] Enable parallel redering of previews for PDF resources

**Comment by mdrlzy** [comment]
> Previews of landscape-oriented documents are generated by this PR version in portrait layout, they are just turned clockwise. Not sure if it is a problem, anyway should be possible to fix easily:

Maybe the wrong orientation is because of this?
`.rotate_if_landscape(PdfBitmapRotation::Degrees90, true);`
https://github.com/ARK-Builders/arklib/blob/868f4586ddc62c8f438a2cd8ddd0d527f3af1452/src/pdf.rs#L45

**Comment by kirillt** [comment]
@mdrlzy I just realized that we can just implement sequential rendering of PDF previews using just some shared **atomic** variable `PDF_JOBS`. Each PDF coroutine checks `PDF_JOBS` and if it is equal than pre-defined limit (1 or 2) then the coroutine sleeps. Should be easier than doing some thread-pool magic. But the variable must be atomic (i.e. support atomic increment/decrement/equality-check).

**Comment by kirillt** [comment]
Superseded by https://github.com/ARK-Builders/ARK-Navigator/pull/329

**Comment by kirillt** [comment]
Superseded https://github.com/ARK-Builders/ARK-Navigator/pull/329

**Pull request closed without merging**
