### PR TITLE
#104: Full screen glitch fix

### PR DESCRIPTION
**Pull request by mdrlzy**
Issue covered #104

### CODE REVIEW

**Comment by CloudLevi** [comment]
Fixed the issue. I was able to reproduce it with a device that has no typical navigation bar at the bottom (home button, back button and active apps button). On some devices, i's possible to toggle the bottom bar on or off. This fix takes care of both cases.

**Comment by kirillt** [comment]
@CloudLevi thanks, I don't have navigation bar indeed on both of my devices.

**Comment by kirillt** [comment]
@CloudLevi that's how it works on my Android 9
bug

**Comment by vedranqa** [comment]
> Fixed the issue. I was able to reproduce it with a device that has no typical navigation bar at the bottom (home button, back button and active apps button). On some devices, i's possible to toggle the bottom bar on or off. This fix takes care of both cases.

When I turn on three button gesture, I have this scenario with bigger white stripes, as you will see in the video:


https://user-images.githubusercontent.com/60543054/145632927-849837a4-d86b-4e01-a7ba-35ae01b75d78.mp4


Xiaomi A2
Android 10
Build: 181

**Comment by CloudLevi** [comment]
> > Fixed the issue. I was able to reproduce it with a device that has no typical navigation bar at the bottom (home button, back button and active apps button). On some devices, i's possible to toggle the bottom bar on or off. This fix takes care of both cases.
> 
> When I turn on three button gesture, I have this scenario with bigger white stripes, as you will see in the video:
> 
>  0-02-0a-0987084a74e0b301e112a1d5161466a938024a6b350947f7bc54ab6ca1920a1f_8c8f4100f10e2446.mp4 
> Xiaomi A2 Android 10 Build: 181

The issue initially was when entering full-screen mode. After searching through many pages of proposed solutions online, that's the best I could do. I believe this comes more from poor handling of content by the Android system. It's easy for the devices to hide the bars with a fancy swipe animation. However, when we exit full-screen mode, I believe it reserves space for navigation and notification bars (hence the white bars), while it's showing a fancy swipe animation. As for the current solution - it works well on some phones, but for others, exiting fullscreen leads to this visual glitch.

I think one of the possible solutions is to have semi-transparent navigation and notification bars all the time when entering the GalleryFragment. This way, content won't have to be resized by the Adnroid system, and the behaviour will be consistent across all devices. What do you think?

See image for better understanding of the proposed solution.
image

**Comment by kirillt** [comment]
@CloudLevi I think semi-transparent and/or floating controls is the way to go

**Comment by kirillt** [comment]
Looks good, @vedranqa could you test it one more time?

**Comment by vedranqa** [comment]
@kirillt this is ok now.

**Review by kirillt — APPROVED** [review]
Looks cool now, thanks

**Pull request merged**
